out: main.c chunk.c debug.c memory.c value.c vm.c compiler.c scanner.c object.c table.c
	gcc -Wall -g main.c chunk.c debug.c memory.c value.c vm.c compiler.c scanner.c object.c table.c -o ../out/clox
